### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by rdperinazzo** [MahmoudAlyuDeen/FirebaseIM#2]
![screenshot_2018-03-17-18-49-55 1](https://user-images.githubusercontent.com/28332114/37606824-2c460044-2b75-11e8-915b-5e497494c9ad.png)

Error in position of the message of who sends, how to solve the problem? Thank you.

**Comment by rdperinazzo** [comment]
![screenshot_2018-03-17-18-43-58-1 1](https://user-images.githubusercontent.com/28332114/37607015-a4b73570-2b75-11e8-9df0-1f8b82a30553.png)
Error in position of the message of who sends, how to solve the problem? Thank you.
When sending the message this is above the last message sent ...

**Comment by MahmoudAlyuDeen** [comment]
Can you make sure the time is set correctly on both devices?

**Comment by rdperinazzo** [comment]
Thank you miss you so much ...
