### ISSUE TITLE
Where to put index.js file for Notification

### ISSUE THREAD

**Issue by vishalchhodwani1992** [MahmoudAlyuDeen/FirebaseIM#5]
Hey MahmoudAlyuDeen,

I just go through your code and the main thing I came for Chat Notifications.

Actually I am confused from where notifications are generated, from our dedicated server or from Firebase itself?

As you said that this is serverless Notification, then it clearly says, It will not be our dedicated server right?

I seen your file index.js and want to know where should I put this file to enable notification.

Can you Please explain me how tho achieve this ?

**Comment by MahmoudAlyuDeen** [comment]
`index.js` is the main entry point for your Cloud Functions application,
it's built and hosted on firebase infrastructure. All you need to do is:
1. Initialize the project.
2. Edit `index.js`.
3. Deploy to firebase using their command line interface.

All these steps are listed in details in their Getting Started guide here
https://firebase.google.com/docs/functions/get-started

**Comment by iruvingu** [comment]
Hey Vishalch!

If you want a better explanation about functions you can check this tutorial.
https://youtu.be/Abh3r9hh5gw

He shows you how to install firebase tools for function and what optiones you have to check for the function.

**Comment by vishalchhodwani1992** [comment]
Thank you MahmoudAlyuDeen and iruvingu for your quick response.

It really helped me. :+1:
